Feature/fix error when pswp container is hidden (#16)
* Update Webpack and Webpack CLI to fix build error (see detailed message)

> webpack -p
<...>/vue-picture-swipe/node_modules/webpack-cli/bin/config-yargs.js:89
                describe: optionsSchema.definitions.output.properties.path.description,

TypeError: Cannot read property 'properties' of undefined
    at module.exports (<...>/vue-picture-swipe/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at <...>/vue-picture-swipe/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (<...>/vue-picture-swipe/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-picture-swipe@0.4.0 build: `webpack -p`
npm ERR! Exit status 1
                                                           ^

* Fix JavaScript error when opening overlay from one of multiple instances (see detailed message)

--- Original JavaScript error ---

photoswipe.js?c3be:510 Uncaught TypeError: Cannot read property 'x' of undefined
    at _equalizePoints (photoswipe.js?c3be:510)
    at eval (photoswipe.js?c3be:2631)
_equalizePoints @ photoswipe.js?c3be:510
(anonymous) @ photoswipe.js?c3be:2631
setTimeout (async)
startAnimation @ photoswipe.js?c3be:2618
_showOrHide @ photoswipe.js?c3be:2684
setContent @ photoswipe.js?c3be:3167
init @ photoswipe.js?c3be:955
openPhotoSwipe @ VuePictureSwipe.vue?4249:285
onThumbnailsClick @ VuePictureSwipe.vue?4249:196

--- How to reproduce ---

Scenario: Two <div>s serving as "tab"-style containers, meaning only one is visible simultaneously (e. g. via "v-show").
Every <div> contains a single VuePictureSwipe instance.

1. With first tab visible, click any thumbnail in first tab container. -> Overlay opens as expected.
2. Select second tab, click any thumbnail in second tab container. -> Overlay does not open due to JavaScript error.

Note that the issue does not appear when using "v-if" - which was not feasible in my particular situation.

--- Fix ---

Since every VuePictureSwipe instance has its own ".pwsp" overlay element, it should be used, thus avoiding PhotoSwipe failing to use a hidden element.

* Rebuild project