Update Webpack and Webpack CLI to fix build error (see detailed message)
> webpack -p
<...>/vue-picture-swipe/node_modules/webpack-cli/bin/config-yargs.js:89
                describe: optionsSchema.definitions.output.properties.path.description,

TypeError: Cannot read property 'properties' of undefined
    at module.exports (<...>/vue-picture-swipe/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at <...>/vue-picture-swipe/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (<...>/vue-picture-swipe/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-picture-swipe@0.4.0 build: `webpack -p`
npm ERR! Exit status 1
                                                           ^